version: '2'

services:
  web:
    restart: always
    build: .
    expose:
      - '8011'
      - '4331'
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=interlinerecords.com,www.interlinerecords.com
      - LETSENCRYPT_HOST=interlinerecords.com,www.interlinerecords.com
      - LETSENCRYPT_EMAIL=info@interlinerecords.com
      - LETSENCRYPT_TEST=true

networks:
  proxy:
    external:
      name: proxy